spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Mysql?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: karol
  jpa:
    hibernate:
      ddl-auto: create